//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authenticity.CourtSide.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Authenticity.CourtSide.Core.Resources.EmailTemplates", typeof(EmailTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear [FirstName] [LastName],&lt;/p&gt;
        ///&lt;p&gt;Your CourtSide password has been reset. To create a new password, click the link below and follow the instructions. Your temporary password is &lt;bold&gt;[TemporaryPassword]&lt;/bold&gt;:&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;[Url]&quot;&gt;CourtSide Password Recovery&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        internal static string UserForgotPasswordBody {
            get {
                return ResourceManager.GetString("UserForgotPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear [FirstName] [LastName],&lt;/p&gt;
        ///&lt;p&gt;Your CourtSide password has been reset, click the link below and follow the instructions:&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;[Url]&quot;&gt;CourtSide Reset Account Password&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        internal static string UserResetPasswordBody {
            get {
                return ResourceManager.GetString("UserResetPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear [FirstName] [LastName],&lt;/p&gt;
        ///&lt;p&gt;Your CourtSide account has been set up. To activate your account, click the link below and follow the instructions:&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;[Url]&quot;&gt;CourtSide Account Activation&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        internal static string UserSetupBody {
            get {
                return ResourceManager.GetString("UserSetupBody", resourceCulture);
            }
        }
    }
}
