//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authenticity.CourtSide.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlStatement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlStatement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Authenticity.CourtSide.Core.Resources.SqlStatement", typeof(SqlStatement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Court] ([TranscriptId], [Name], [Address], [City], [State], [Zipcode], [CreatedBy], [CreatedOn])
        ///VALUES (@TranscriptId, @Name, @Address, @City, @State, @Zipcode, @CreatedBy, GETUTCDATE());
        ///SELECT CAST(SCOPE_IDENTITY() as int).
        /// </summary>
        internal static string Court_Create {
            get {
                return ResourceManager.GetString("Court_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [dbo].[Court] WHERE [TranscriptId] = @TranscriptId.
        /// </summary>
        internal static string Court_DeleteByTranscriptId {
            get {
                return ResourceManager.GetString("Court_DeleteByTranscriptId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    C.[Id], 
        ///    C.[TranscriptId], 
        ///    C.[Name],
        ///    C.[Address],
        ///	C.[City],
        ///	C.[State],
        ///	C.[Zipcode],
        ///    C.CreatedBy,
        ///    C.CreatedOn,
        ///    C.LastModifiedBy,
        ///    C.LastModifiedOn
        ///FROM [dbo].[Court] AS C WITH(NOLOCK)
        ///WHERE C.[Id] =@Id;.
        /// </summary>
        internal static string Court_GetById {
            get {
                return ResourceManager.GetString("Court_GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    C.[Id], 
        ///    C.[TranscriptId], 
        ///    C.[Name],
        ///    C.[Address],
        ///	C.[City],
        ///	C.[State],
        ///	C.[Zipcode],
        ///    C.CreatedBy,
        ///    C.CreatedOn,
        ///    C.LastModifiedBy,
        ///    C.LastModifiedOn
        ///FROM [dbo].[Court] AS C WITH(NOLOCK)
        ///WHERE C.[TranscriptId] =@TranscriptId;.
        /// </summary>
        internal static string Court_GetByTranscriptId {
            get {
                return ResourceManager.GetString("Court_GetByTranscriptId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Court] SET
        ///    [TranscriptId] = @TranscriptId, 
        ///    [Name] = @Name,
        ///    [Address] = @Address,
        ///	[City] = @City,
        ///	[State] = @State,
        ///	[Zipcode] = @Zipcode,
        ///    LastModifiedBy = @LastModifiedBy,
        ///    LastModifiedOn = GETUTCDATE()
        ///WHERE [Id] = @CourtId.
        /// </summary>
        internal static string Court_Update {
            get {
                return ResourceManager.GetString("Court_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    Id, 
        ///    [Path],
        ///	[FileName],
        ///	[FormatName],
        ///	[Type],
        ///	[CreatedBy],
        ///	[CreatedOn]
        ///FROM [dbo].[FileExportFormat] WITH(NOLOCK)
        ///WHERE [Type] = @Type AND [FormatName] = @FormatName.
        /// </summary>
        internal static string FileFormat_GetByFormatNameAndType {
            get {
                return ResourceManager.GetString("FileFormat_GetByFormatNameAndType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    Id, 
        ///    [Path],
        ///	[FileName],
        ///	[FormatName],
        ///	[Type],
        ///	[CreatedBy],
        ///	[CreatedOn]
        ///FROM [dbo].[FileExportFormat] WITH(NOLOCK)
        ///WHERE Id =@FormatId;.
        /// </summary>
        internal static string FileFormat_GetFormatById {
            get {
                return ResourceManager.GetString("FileFormat_GetFormatById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[FileProvider] ([Name], [Parameters], [IsCurrentProvider], [CreatedBy], [CreatedOn])
        ///VALUES (@Name, @Parameters, @IsCurrentProvider, @CreatedBy, GETUTCDATE());
        ///DECLARE @FileProviderCreatedId INT = (SELECT CAST(SCOPE_IDENTITY() as int))
        ///
        ///IF @IsCurrentProvider = 1
        ///BEGIN
        ///    UPDATE [dbo].[FileProvider]
        ///    SET [IsCurrentProvider] = 0
        ///    WHERE [Id] &lt;&gt; @FileProviderCreatedId
        ///END
        ///
        ///SELECT @FileProviderCreatedId.
        /// </summary>
        internal static string FileProvider_CreateFileProvider {
            get {
                return ResourceManager.GetString("FileProvider_CreateFileProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[Name]
        ///      ,[Parameters]
        ///      ,[IsCurrentProvider]
        ///      ,[CreatedBy]
        ///      ,[CreatedOn]
        ///      ,[LastModifiedBy]
        ///      ,[LastModifiedOn]
        ///FROM [dbo].[FileProvider] WITH (NOLOCK).
        /// </summary>
        internal static string FileProvider_GetAllFileProviders {
            get {
                return ResourceManager.GetString("FileProvider_GetAllFileProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[Name]
        ///      ,[Parameters]
        ///      ,[IsCurrentProvider]
        ///      ,[CreatedBy]
        ///      ,[CreatedOn]
        ///      ,[LastModifiedBy]
        ///      ,[LastModifiedOn]
        ///FROM [dbo].[FileProvider] WITH (NOLOCK)
        ///WHERE [IsCurrentProvider] = 1.
        /// </summary>
        internal static string FileProvider_GetCurrentFileProvider {
            get {
                return ResourceManager.GetString("FileProvider_GetCurrentFileProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[Name]
        ///      ,[Parameters]
        ///      ,[IsCurrentProvider]
        ///      ,[CreatedBy]
        ///      ,[CreatedOn]
        ///      ,[LastModifiedBy]
        ///      ,[LastModifiedOn]
        ///FROM [dbo].[FileProvider] WITH (NOLOCK)
        ///WHERE [Id] = @FileProviderId.
        /// </summary>
        internal static string FileProvider_GetFileProviderById {
            get {
                return ResourceManager.GetString("FileProvider_GetFileProviderById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [FileProvider] 
        ///SET
        ///	[Name] = @Name,
        ///	[Parameters] = @Parameters,
        ///	[IsCurrentProvider] = @IsCurrentProvider,
        ///	[LastModifiedBy] = @LastModifiedBy,
        ///	[LastModifiedOn] = GETUTCDATE()
        ///WHERE Id = @Id
        ///
        ///IF @IsCurrentProvider = 1
        ///BEGIN
        ///    UPDATE [dbo].[FileProvider]
        ///    SET [IsCurrentProvider] = 0
        ///    WHERE [Id] &lt;&gt; @Id
        ///END.
        /// </summary>
        internal static string FileProvider_UpdateFileProvider {
            get {
                return ResourceManager.GetString("FileProvider_UpdateFileProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        /// [Id] AS [ApiLanguageId]
        ///,[LanguageType]
        ///,[Name]
        ///,[ApiCode]
        ///,[GenericCode]
        ///,[CreatedBy]
        ///,[CreatedOn]
        ///,[LastModifiedBy]
        ///,[LastModifiedOn]
        ///FROM [dbo].[Language] WITH (NOLOCK)
        ///WHERE [Id] =@LanguageId;.
        /// </summary>
        internal static string Language_GetById {
            get {
                return ResourceManager.GetString("Language_GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        /// [Id] AS [ApiLanguageId]
        ///,[LanguageType]
        ///,[Name]
        ///,[ApiCode]
        ///,[GenericCode]
        ///,[CreatedBy]
        ///,[CreatedOn]
        ///,[LastModifiedBy]
        ///,[LastModifiedOn]
        /// FROM [dbo].[Language] WITH (NOLOCK)
        /// WHERE [LanguageType] = @LanguageType.
        /// </summary>
        internal static string Language_GetByType {
            get {
                return ResourceManager.GetString("Language_GetByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    O.Id, 
        ///    O.Name, 
        ///    P.Id AS PermissionId,
        ///    P.Name
        ///FROM [dbo].[Role] AS R WITH(NOLOCK)
        ///JOIN [dbo].[User_Role] AS UR WITH(NOLOCK) ON R.Id = UR.RoleId
        ///JOIN [dbo].[Role_ObjectPermission] AS ROP WITH(NOLOCK) ON R.Id = ROP.RoleId
        ///JOIN [dbo].[Object_Permission] AS OP WITH(NOLOCK) ON ROP.ObjectPermissionId = OP.Id
        ///JOIN [dbo].[Object] AS O WITH(NOLOCK) ON OP.ObjectId = O.Id
        ///JOIN [dbo].[Permission] AS P WITH(NOLOCK) ON OP.PermissionId = P.Id
        ///WHERE UR.UserId =@UserId;.
        /// </summary>
        internal static string Permission_GetAllObjectPermissionByUser {
            get {
                return ResourceManager.GetString("Permission_GetAllObjectPermissionByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    R.Id as RoleId,
        ///    R.Name,
        ///    OP.Id AS ObjectPermissionId, 
        ///    P.Id AS PermissionId,
        ///	P.Name AS PermissionName,
        ///    O.Id AS ObjectId,
        ///    O.Name AS ObjectName
        ///FROM [dbo].[Role] AS R WITH(NOLOCK)
        ///JOIN [dbo].[Role_ObjectPermission] AS ROP WITH(NOLOCK) ON R.Id = ROP.RoleId
        ///JOIN [dbo].[Object_Permission] AS OP WITH(NOLOCK) ON ROP.ObjectPermissionId = OP.Id
        ///JOIN [dbo].[Object] AS O WITH(NOLOCK) ON OP.ObjectId = O.Id
        ///JOIN [dbo].[Permission] AS P WITH(NOLOCK) ON OP.PermissionId = P.Id.
        /// </summary>
        internal static string Permission_GetAllRolesWithObjectPermission {
            get {
                return ResourceManager.GetString("Permission_GetAllRolesWithObjectPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [PersonalAdditionalInformation] ([BarNumber], [Title], [Address], [Telephone], [LegalFirm])
        ///VALUES (@BarNumber, @Title, @Address, @Telephone, @LegalFirm);
        ///SELECT CAST(SCOPE_IDENTITY() as int).
        /// </summary>
        internal static string PersonInformation_Create {
            get {
                return ResourceManager.GetString("PersonInformation_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [PersonalAdditionalInformation]
        ///WHERE [Id] = @PersonAdditionalInformationId.
        /// </summary>
        internal static string PersonInformation_Delete {
            get {
                return ResourceManager.GetString("PersonInformation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///UPDATE [PersonalAdditionalInformation] SET
        ///    [BarNumber] = @BarNumber, 
        ///    [Title] = @Title,
        ///    [Address] = @Address,	
        ///	[Telephone] = @Telephone,
        ///    [LegalFirm] = @LegalFirm
        ///WHERE [Id] = @PersonAdditionalInformationId.
        /// </summary>
        internal static string PersonInformation_Update {
            get {
                return ResourceManager.GetString("PersonInformation_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [TranscriptRecordingInfo] ([TranscriptId], [VenueCompany], [StreetAddress], [City], [State], [Zipcode], [CreatedBy], [CreatedOn])
        ///VALUES (@TranscriptId, @VenueCompany, @StreetAddress, @City, @State, @Zipcode, @CreatedBy, GETUTCDATE());
        ///SELECT CAST(SCOPE_IDENTITY() as int).
        /// </summary>
        internal static string RecordingInfo_Create {
            get {
                return ResourceManager.GetString("RecordingInfo_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [dbo].[TranscriptRecordingInfo]
        ///WHERE [TranscriptId] = @TranscriptId.
        /// </summary>
        internal static string RecordingInfo_DeleteByTranscriptId {
            get {
                return ResourceManager.GetString("RecordingInfo_DeleteByTranscriptId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    [Id],
        ///    [TranscriptId], 
        ///    [VenueCompany],
        ///    [StreetAddress],
        ///	[City],
        ///	[State],
        ///	[Zipcode],
        ///    CreatedBy,
        ///    CreatedOn,
        ///    LastModifiedBy,
        ///    LastModifiedOn
        ///FROM [dbo].[TranscriptRecordingInfo] WITH(NOLOCK)
        ///WHERE [Id] = @Id;.
        /// </summary>
        internal static string RecordingInfo_GetById {
            get {
                return ResourceManager.GetString("RecordingInfo_GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    [Id],
        ///    [TranscriptId], 
        ///    [VenueCompany],
        ///    [StreetAddress],
        ///	[City],
        ///	[State],
        ///	[Zipcode],
        ///    CreatedBy,
        ///    CreatedOn,
        ///    LastModifiedBy,
        ///    LastModifiedOn
        ///FROM [dbo].[TranscriptRecordingInfo] WITH(NOLOCK)
        ///WHERE [TranscriptId] = @TranscriptId;.
        /// </summary>
        internal static string RecordingInfo_GetByTranscriptId {
            get {
                return ResourceManager.GetString("RecordingInfo_GetByTranscriptId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [TranscriptRecordingInfo] SET
        ///    [TranscriptId] = @TranscriptId, 
        ///    [VenueCompany] = @VenueCompany,
        ///    [StreetAddress] = @StreetAddress,
        ///	[City] = @City,
        ///	[State] = @State,
        ///	[Zipcode] = @Zipcode,
        ///    LastModifiedBy = @LastModifiedBy,
        ///    LastModifiedOn = GETUTCDATE()
        ///WHERE [Id] = @TranscriptRecordingInfoId.
        /// </summary>
        internal static string RecordingInfo_Update {
            get {
                return ResourceManager.GetString("RecordingInfo_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    [Id] [RoleId],
        ///    [Name],
        ///    [CreatedOn],
        ///    [CreatedBy],
        ///    [LastModifiedOn],
        ///    [LastModifiedBy]
        ///FROM [Role] WITH (NOLOCK).
        /// </summary>
        internal static string Role_GetAllRoles {
            get {
                return ResourceManager.GetString("Role_GetAllRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [TranscriptJob] SET
        ///	[Status] = 5
        ///WHERE [TranscriptId] = @TranscriptId
        ///	AND [Status] NOT IN (2, 5).
        /// </summary>
        internal static string Transcript_CancelJobsInProgress {
            get {
                return ResourceManager.GetString("Transcript_CancelJobsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CAST(1 AS BIT)
        ///FROM [dbo].[Transcript] WITH(NOLOCK)
        ///WHERE [Id] = @TranscriptId AND [CreatedBy] = @UserId.
        /// </summary>
        internal static string Transcript_CheckUser {
            get {
                return ResourceManager.GetString("Transcript_CheckUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[Transcript_Dialog] (
        ///	[TranscriptId], 
        ///	[PersonId], 
        ///	[StartTime], 
        ///	[Duration], 
        ///	[Transcription], 
        ///	[OriginalSpeakerId],
        ///	[OriginalSpeakerName],
        ///	[ExaminationType],
        ///	[ExaminationTag]) 
        ///VALUES (
        ///	@TranscriptId, 
        ///	NULL, 
        ///	@StartTime, 
        ///	@Duration, 
        ///	@Transcription, 
        ///	@OriginalSpeakerId,
        ///	@OriginalSpeakerName,
        ///	@ExaminationType,
        ///	@ExaminationTag);
        ///SELECT CAST(SCOPE_IDENTITY() as int).
        /// </summary>
        internal static string Transcript_CreateDialog {
            get {
                return ResourceManager.GetString("Transcript_CreateDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [TranscriptJob] ([TranscriptId], [Guid], [Status], [ApiUrl], [TranscriptionEngine], [Message], [CreatedBy], [CreatedOn])
        ///VALUES (@TranscriptId, @JobGuid, @Status, @ApiUrl, @TranscriptionEngine, @Message, @CreatedBy, GETUTCDATE());
        ///SELECT CAST(SCOPE_IDENTITY() as int).
        /// </summary>
        internal static string Transcript_CreateJob {
            get {
                return ResourceManager.GetString("Transcript_CreateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [TranscriptFile] ([TranscriptId], [Name], [Path], [CreatedOn])
        ///VALUES (@TranscriptId, @Name, @Path, GETUTCDATE());
        ///SELECT CAST(SCOPE_IDENTITY() as int).
        /// </summary>
        internal static string Transcript_CreateMediaFile {
            get {
                return ResourceManager.GetString("Transcript_CreateMediaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [TranscriptPerson] ([FirstName], [MiddleName], [LastName], [TypeId], [TranscriptId], [CreatedBy], [CreatedOn])
        ///VALUES (@FirstName, @MiddleName, @LastName, @Type, @TranscriptId, @CreatedBy, GETUTCDATE());
        ///SELECT CAST(SCOPE_IDENTITY() as int).
        /// </summary>
        internal static string Transcript_CreatePerson {
            get {
                return ResourceManager.GetString("Transcript_CreatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Transcript] ([Name], [MediaFileSize], [Status], [Step], [CreatedBy], [CreatedOn])
        ///VALUES (@Name, 0, 0, 1, @CreatedBy, GETUTCDATE());
        ///SELECT CAST(SCOPE_IDENTITY() as int).
        /// </summary>
        internal static string Transcript_CreateWithName {
            get {
                return ResourceManager.GetString("Transcript_CreateWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [dbo].[Transcript] WHERE [Id] = @TranscriptId.
        /// </summary>
        internal static string Transcript_Delete {
            get {
                return ResourceManager.GetString("Transcript_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [dbo].[TranscriptJob] WHERE [TranscriptId] = @TranscriptId.
        /// </summary>
        internal static string Transcript_DeleteAllJobsByTranscriptId {
            get {
                return ResourceManager.GetString("Transcript_DeleteAllJobsByTranscriptId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE [dbo].[PersonalAdditionalInformation]
        ///FROM [dbo].[PersonalAdditionalInformation] PAI
        ///    RIGHT JOIN [dbo].[TranscriptPerson] TP ON PAI.Id = TP.PersonAdditionalInformationId
        ///WHERE TP.[TranscriptId] = @TranscriptId
        ///
        ///DELETE FROM [dbo].[TranscriptPerson]
        ///WHERE [TranscriptId] = @TranscriptId.
        /// </summary>
        internal static string Transcript_DeleteAllPeopleByTranscriptId {
            get {
                return ResourceManager.GetString("Transcript_DeleteAllPeopleByTranscriptId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [dbo].[Transcript_Dialog] WHERE [TranscriptId] = @TranscriptId.
        /// </summary>
        internal static string Transcript_DeleteDialogsByTranscriptId {
            get {
                return ResourceManager.GetString("Transcript_DeleteDialogsByTranscriptId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [TranscriptFile] WHERE [TranscriptId] = @TranscriptId.
        /// </summary>
        internal static string Transcript_DeleteDuplicatedFiles {
            get {
                return ResourceManager.GetString("Transcript_DeleteDuplicatedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [dbo].[TranscriptFile] WHERE [TranscriptId] = @TranscriptId.
        /// </summary>
        internal static string Transcript_DeleteFilesByTranscriptId {
            get {
                return ResourceManager.GetString("Transcript_DeleteFilesByTranscriptId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DELETE FROM [TranscriptPerson]
        ///WHERE [Id] = @PersonId.
        /// </summary>
        internal static string Transcript_DeletePerson {
            get {
                return ResourceManager.GetString("Transcript_DeletePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    TJ.Id, 
        ///    TJ.TranscriptId,
        ///    TJ.[Guid] AS JobGuid,
        ///    TJ.[Status],
        ///    TJ.[Message],
        ///    TJ.[StartSendingToApiOn],
        ///    TJ.[SentToApiOn],
        ///    TJ.[CompletedOn],
        ///    TJ.CreatedBy,
        ///    TJ.CreatedOn
        ///FROM [dbo].[TranscriptJob] AS TJ WITH(NOLOCK)
        ///WHERE TJ.[TranscriptId] = @TranscriptId AND [Status] != 5
        ///ORDER BY TJ.CreatedOn;.
        /// </summary>
        internal static string Transcript_GetActiveJobByTranscriptId {
            get {
                return ResourceManager.GetString("Transcript_GetActiveJobByTranscriptId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT 
        ///    T.Id, 
        ///    T.Name, 
        ///    T.MediaFileSize,
        ///    T.[Status],
        ///    T.[Step],
        ///    T.TranscriptDateTime AS RecordDate,
        ///    T.DeptNumber,
        ///    T.TranscriptType,
        ///    T.Locked,
        ///    T.CreatedBy,
        ///    T.CreatedOn,
        ///    T.LastModifiedOn,
        ///    T.LastModifiedBy
        ///FROM [dbo].[Transcript] AS T WITH(NOLOCK)
        ///WHERE T.CreatedBy =@UserId;.
        /// </summary>
        internal static string Transcript_GetAllByUser {
            get {
                return ResourceManager.GetString("Transcript_GetAllByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    TP.Id, 
        ///    [TranscriptId],
        ///	[OriginalSpeakerId],
        ///	[OriginalSpeakerName],
        ///	[PersonId],
        ///	[StartTime],
        ///	[Duration],
        ///	[Transcription],
        ///	[ExaminationType],
        ///	[ExaminationTag]
        ///FROM [dbo].[Transcript_Dialog] AS TP WITH(NOLOCK)
        ///WHERE TP.TranscriptId =@TranscriptId
        ///ORDER BY [StartTime] ASC;.
        /// </summary>
        internal static string Transcript_GetAllDialogsByTranscriptId {
            get {
                return ResourceManager.GetString("Transcript_GetAllDialogsByTranscriptId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    TP.Id, 
        ///    [TranscriptId],
        ///	[OriginalSpeakerId],
        ///	[OriginalSpeakerName],
        ///	[PersonId],
        ///	[StartTime],
        ///	[Duration],
        ///	[Transcription],
        ///	[ExaminationType],
        ///	[ExaminationTag]
        ///FROM [dbo].[Transcript_Dialog] AS TP WITH(NOLOCK)
        ///WHERE TP.TranscriptId =@TranscriptId
        ///ORDER BY [StartTime] ASC
        ///OFFSET 100*(@Page-1) ROWS FETCH NEXT 100 ROWS ONLY;.
        /// </summary>
        internal static string Transcript_GetAllDialogsByTranscriptIdAndPage {
            get {
                return ResourceManager.GetString("Transcript_GetAllDialogsByTranscriptIdAndPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    TP.Id, 
        ///    TP.[Name], 
        ///    TP.TranscriptId,
        ///    TP.[Path],
        ///    TP.CreatedOn
        ///FROM [dbo].[TranscriptFile] AS TP WITH(NOLOCK)
        ///WHERE TP.TranscriptId =@TranscriptId;.
        /// </summary>
        internal static string Transcript_GetAllFilesByTranscriptId {
            get {
                return ResourceManager.GetString("Transcript_GetAllFilesByTranscriptId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    TP.Id, 
        ///    TP.[Name], 
        ///    TP.TranscriptId,
        ///    TP.[Path],
        ///    TP.CreatedOn
        ///FROM [dbo].[TranscriptFile] AS TP WITH(NOLOCK) 
        ///INNER JOIN [dbo].[Transcript] AS T WITH(NOLOCK) ON TP.TranscriptId = T.Id
        ///WHERE T.CreatedBy = @UserId
        ///ORDER BY TP.Id;.
        /// </summary>
        internal static string Transcript_GetAllFilesByUserId {
            get {
                return ResourceManager.GetString("Transcript_GetAllFilesByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    TP.Id, 
        ///    TP.FirstName,
        ///    TP.MiddleName,
        ///    TP.LastName, 
        ///    TP.TypeId AS [Type],
        ///    TP.TranscriptId,
        ///    TP.CreatedBy,
        ///    TP.CreatedOn,
        ///    TP.PersonAdditionalInformationId,
        ///    AI.[BarNumber], 
        ///    AI.[Title], 
        ///    AI.[Address], 
        ///    AI.[Telephone],
        ///    AI.[LegalFirm]
        ///FROM [dbo].[TranscriptPerson] AS TP WITH(NOLOCK) 
        ///LEFT JOIN [dbo].[PersonalAdditionalInformation] AS AI WITH(NOLOCK) ON TP.PersonAdditionalInformationId = AI.Id
        ///WHERE TP.TranscriptId = @TranscriptId
        ///ORDE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Transcript_GetAllPersonsByTranscriptId {
            get {
                return ResourceManager.GetString("Transcript_GetAllPersonsByTranscriptId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERGE INTO [dbo].[TranscriptJob] AS TARGET
        ///USING
        ///(
        ///    SELECT TOP 5
        ///        Id, 
        ///        TranscriptId,
        ///        [Guid],
        ///        [Status],
        ///        [ApiUrl],
        ///        [TranscriptionEngine],
        ///        [Message],
        ///        [StartSendingToApiOn],
        ///        [SentToApiOn],
        ///        [CompletedOn],
        ///        CreatedBy,
        ///        CreatedOn
        ///    FROM [dbo].[TranscriptJob]
        ///    WHERE [Status] =  @Status
        ///) AS SOURCE
        ///ON TARGET.[Id] = SOURCE.[Id]
        ///WHEN MATCHED THEN UPDATE SET [Status] = 4
        ///OUTPUT INSERTED.[Id]
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Transcript_GetBatchOfJobsByStatus {
            get {
                return ResourceManager.GetString("Transcript_GetBatchOfJobsByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    TP.Id, 
        ///    TP.FirstName,
        ///    TP.MiddleName,
        ///    TP.LastName, 
        ///    TP.TypeId AS [Type],
        ///    TP.TranscriptId,
        ///    TP.CreatedBy,
        ///    TP.CreatedOn,
        ///    TP.PersonAdditionalInformationId,
        ///    AI.[BarNumber], 
        ///    AI.[Title], 
        ///    AI.[Address], 
        ///    AI.[Telephone],
        ///    AI.[LegalFirm]
        ///FROM [dbo].[TranscriptPerson] AS TP WITH(NOLOCK) 
        ///LEFT JOIN [dbo].[PersonalAdditionalInformation] AS AI WITH(NOLOCK) ON TP.PersonAdditionalInformationId = AI.Id
        ///WHERE TP.Id = @PersonId.
        /// </summary>
        internal static string Transcript_GetPersonById {
            get {
                return ResourceManager.GetString("Transcript_GetPersonById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    T.Id, 
        ///    T.[Name], 
        ///    T.MediaFileSize,
        ///    T.[Status],
        ///    T.[Step],
        ///    T.TranscriptDateTime AS RecordDate,
        ///    T.CaseNumber,
        ///    T.JudgeName,
        ///    T.JudgeTitle,
        ///    T.TranscriptType,
        ///    T.DeptNumber, 
        ///    T.Locked,
        ///    T.ApiLanguageId,
        ///    T.CreatedBy,
        ///    T.CreatedOn,
        ///    T.LastModifiedBy,
        ///    T.LastModifiedOn,
        ///    C.Id AS CourtId,
        ///    C.[Name],
        ///    C.[Address],
        ///    C.[City],
        ///    C.[State],
        ///    C.[Zipcode],
        ///    TRI.[Id] AS TranscriptRecordingInfoId,
        ///    TRI.[Venue [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Transcript_GetTranscriptById {
            get {
                return ResourceManager.GetString("Transcript_GetTranscriptById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Transcript] SET 
        ///	[Locked] = @Locked,
        ///	[LastModifiedBy] = @LastModifiedBy,
        ///	[LastModifiedOn] = GETUTCDATE()
        ///WHERE Id = @TranscriptId.
        /// </summary>
        internal static string Transcript_LockById {
            get {
                return ResourceManager.GetString("Transcript_LockById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[Transcript_Dialog] SET
        ///	[ExaminationType] = @ExaminationType,
        ///	[ExaminationTag] = @ExaminationTag
        ///WHERE [TranscriptId] = @TranscriptId
        ///	AND [Id] &gt;= @StartId
        ///	AND [Id] &lt;= @EndId;
        ///
        ///select @@ROWCOUNT;.
        /// </summary>
        internal static string Transcript_SaveExamination {
            get {
                return ResourceManager.GetString("Transcript_SaveExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @OriginalSpeakerId AS INT;
        ///SELECT @OriginalSpeakerId = [OriginalSpeakerId]
        ///FROM [Transcript_Dialog] WITH(NOLOCK)
        ///WHERE [Id] = @Id;
        ///
        ///UPDATE [Transcript_Dialog] SET
        ///	[PersonId] = @PersonId
        ///WHERE [OriginalSpeakerId] = @OriginalSpeakerId
        ///    AND [TranscriptId] = @TranscriptId.
        /// </summary>
        internal static string Transcript_UpdateAllSpeakers {
            get {
                return ResourceManager.GetString("Transcript_UpdateAllSpeakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Transcript_Dialog] SET
        ///	[PersonId] = @PersonId, 
        ///	[Transcription] = @Transcription
        ///WHERE [Id] = @Id.
        /// </summary>
        internal static string Transcript_UpdateDialog {
            get {
                return ResourceManager.GetString("Transcript_UpdateDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Avoid to update a canceled job
        ///IF NOT EXISTS ( SELECT 1 FROM [dbo].[TranscriptJob] WHERE [Id] = @Id AND [Status] = 5 )
        ///BEGIN
        ///	UPDATE [TranscriptJob] SET
        ///		[Guid] = @JobGuid,
        ///		[Status] = @Status,
        ///		[Message] = @Message,
        ///        [StartSendingToApiOn] = @StartSendingToApiOn,
        ///        [SentToApiOn] = @SentToApiOn,
        ///        [CompletedOn] = @CompletedOn
        ///	WHERE [Id] = @Id
        ///END.
        /// </summary>
        internal static string Transcript_UpdateJob {
            get {
                return ResourceManager.GetString("Transcript_UpdateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[Transcript_Dialog]
        ///SET [ExaminationTag] = @ExaminationTag
        ///WHERE [TranscriptId] = @TranscriptId
        ///	AND [OriginalSpeakerId] = @OriginalSpeakerId
        ///	AND [Id] &gt;= @StartId
        ///	AND [Id] &lt;= @EndId;
        ///
        ///select @@ROWCOUNT;.
        /// </summary>
        internal static string Transcript_UpdateMassiveExaminationTag {
            get {
                return ResourceManager.GetString("Transcript_UpdateMassiveExaminationTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///UPDATE [TranscriptPerson] SET
        ///	[FirstName] = @FirstName,
        ///	[MiddleName] = @MiddleName,
        ///	[LastName] = @LastName,
        ///	[PersonAdditionalInformationId] = @PersonAdditionalInformationId
        ///WHERE [Id] = @Id.
        /// </summary>
        internal static string Transcript_UpdatePerson {
            get {
                return ResourceManager.GetString("Transcript_UpdatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Transcript_Dialog] 
        ///SET [ExaminationTag] = @ExaminationTag, [ExaminationType] = @ExaminationType
        ///WHERE [Id] = @Id AND [TranscriptId] = @TranscriptId.
        /// </summary>
        internal static string Transcript_UpdateSingleExamination {
            get {
                return ResourceManager.GetString("Transcript_UpdateSingleExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Transcript_Dialog] 
        ///SET [ExaminationTag] = @ExaminationTag
        ///WHERE [Id] = @Id AND [TranscriptId] = @TranscriptId.
        /// </summary>
        internal static string Transcript_UpdateSingleExaminationTag {
            get {
                return ResourceManager.GetString("Transcript_UpdateSingleExaminationTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Transcript] SET 
        ///	[Name] = @Name, 
        ///	[MediaFileSize] = @MediaFileSize, 
        ///	[Status] = @Status,
        ///	[Step] = @Step,
        ///	[CaseNumber] = @CaseNumber,
        ///	[JudgeName] = @JudgeName,
        ///	[JudgeTitle] = @JudgeTitle,
        ///	[TranscriptType] = @TranscriptType,
        ///	[DeptNumber] = @DeptNumber,
        ///	[TranscriptDateTime] = @RecordDate,
        ///	[ApiLanguageId] = @ApiLanguageId,
        ///	[LastModifiedBy] = @LastModifiedBy,
        ///	[LastModifiedOn] = GETUTCDATE()
        ///WHERE Id = @Id.
        /// </summary>
        internal static string Transcript_UpdateTranscriptBasicInfo {
            get {
                return ResourceManager.GetString("Transcript_UpdateTranscriptBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Transcript] SET 
        ///	[OriginalTranscriptResponse] = @Transcription, 
        ///	[LastModifiedOn] = GETUTCDATE(),
        ///	[Status] = 2
        ///WHERE Id = @Id.
        /// </summary>
        internal static string Transcript_UpdateTranscriptText {
            get {
                return ResourceManager.GetString("Transcript_UpdateTranscriptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[Name]
        ///      ,[Code]
        ///      ,[CreatedBy]
        ///      ,[CreatedOn]
        ///      ,[LastModifiedBy]
        ///      ,[LastModifiedOn]
        ///FROM [dbo].[TranscriptionEngine] WITH (NOLOCK).
        /// </summary>
        internal static string TranscriptionEngine_GetAll {
            get {
                return ResourceManager.GetString("TranscriptionEngine_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[Name]
        ///      ,[Code]
        ///      ,[CreatedBy]
        ///      ,[CreatedOn]
        ///      ,[LastModifiedBy]
        ///      ,[LastModifiedOn]
        ///FROM [dbo].[TranscriptionEngine] WITH (NOLOCK)
        ///WHERE [Id] = @TranscriptionEngineId.
        /// </summary>
        internal static string TranscriptionEngine_GetById {
            get {
                return ResourceManager.GetString("TranscriptionEngine_GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CAST(1 AS BIT)
        ///FROM [dbo].[User] WITH(NOLOCK)
        ///WHERE [Id] = @UserId AND [TemporalPassword] = @TemporalPassword.
        /// </summary>
        internal static string User_CheckTemporalPassword {
            get {
                return ResourceManager.GetString("User_CheckTemporalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [User] ([FirstName], [LastName], [Email], [Status], [EmailActivationId], [ApiUrl], [ApiGuid], [TranscriptionEngineId], [CreatedBy],[CreatedOn])
        ///VALUES (@FirstName, @LastName, @Email, @Status, @EmailActivationId, @ApiUrl, @ApiGuid, @TranscriptionEngineId, @CreatedBy, GETUTCDATE());
        ///SELECT CAST(SCOPE_IDENTITY() as int).
        /// </summary>
        internal static string User_CreateUser {
            get {
                return ResourceManager.GetString("User_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [UserLoginHistory] ([UserId], [LoginTime])
        ///VALUES (@UserId, GETUTCDATE()).
        /// </summary>
        internal static string User_CreateUserLoginHistory {
            get {
                return ResourceManager.GetString("User_CreateUserLoginHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [User_Role] ([UserId], [RoleId], [CreatedBy], [CreatedOn]) 
        ///VALUES (@UserId, @RoleId, @CreatedBy, GETUTCDATE());.
        /// </summary>
        internal static string User_CreateUserRole {
            get {
                return ResourceManager.GetString("User_CreateUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM dbo.[UserLoginHistory] WHERE [UserId] = @UserId;
        ///DELETE FROM dbo.[User_Role] where [UserId] = @UserId;
        ///DELETE FROM dbo.[User] where [Id] = @UserId;
        ///
        ///SELECT @@ROWCOUNT;.
        /// </summary>
        internal static string User_DeleteUser {
            get {
                return ResourceManager.GetString("User_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [User] 
        ///SET 
        ///	[FirstName] = @FirstName,
        ///	[LastName] = @LastName,
        ///	[Email] = @Email, 
        ///	[Status] = @Status,
        ///	[EmailActivationId] = CASE WHEN @EmailActivationId IS NOT NULL THEN @EmailActivationId ELSE [EmailActivationId] END,
        ///	[ApiUrl] = @ApiUrl,
        ///	[ApiGuid] = @ApiGuid,
        ///	[TranscriptionEngineId] = @TranscriptionEngineId,
        ///    [LastModifiedBy] = @LastModifiedBy,
        ///    [LastModifiedOn] = GETUTCDATE() 
        ///WHERE [Id] = @Id.
        /// </summary>
        internal static string User_EditUser {
            get {
                return ResourceManager.GetString("User_EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [User_Role]
        ///SET [RoleId] = @RoleId, [LastModifiedBy] = @LastModifiedBy, [LastModifiedOn] = GETUTCDATE()
        ///WHERE [UserId] = @UserId.
        /// </summary>
        internal static string User_EditUserRole {
            get {
                return ResourceManager.GetString("User_EditUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT
        ///    U.Id
        ///   ,U.FirstName
        ///   ,U.LastName
        ///   ,U.Email
        ///   ,U.Password
        ///   ,U.Status
        ///   ,U.EmailActivationId
        ///   ,U.ApiUrl
        ///   ,U.ApiGuid
        ///   ,U.TranscriptionEngineId
        ///   ,U.CreatedBy
        ///   ,U.CreatedOn
        ///   ,U.LastModifiedBy
        ///   ,U.LastModifiedOn
        ///   ,R.Id RoleId
        ///   ,R.Name
        ///FROM [User] U WITH (NOLOCK)
        ///JOIN User_Role UR
        ///    ON U.Id = UR.UserId
        ///JOIN [Role] R
        ///    ON UR.RoleId = R.Id.
        /// </summary>
        internal static string User_GetAllUsers {
            get {
                return ResourceManager.GetString("User_GetAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    U.Id
        ///   ,U.FirstName
        ///   ,U.LastName
        ///   ,U.Email
        ///   ,U.Password
        ///   ,U.Status
        ///   ,U.EmailActivationId
        ///   ,U.ApiUrl
        ///   ,U.ApiGuid
        ///   ,U.TranscriptionEngineId
        ///   ,U.CreatedBy
        ///   ,U.CreatedOn
        ///   ,U.LastModifiedBy
        ///   ,U.LastModifiedOn
        ///   ,R.Id RoleId
        ///   ,R.Name Name
        ///FROM [User] U WITH (NOLOCK)
        ///JOIN User_Role UR
        ///    ON U.Id = UR.UserId
        ///JOIN [Role] R
        ///    ON UR.RoleId = R.Id
        ///WHERE U.Email = @Email;.
        /// </summary>
        internal static string User_GetUserByEmail {
            get {
                return ResourceManager.GetString("User_GetUserByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    U.Id
        ///   ,U.FirstName
        ///   ,U.LastName
        ///   ,U.Email
        ///   ,U.Password
        ///   ,U.Status
        ///   ,U.EmailActivationId
        ///   ,U.ApiUrl
        ///   ,U.ApiGuid
        ///   ,U.CreatedBy
        ///   ,U.CreatedOn
        ///   ,U.LastModifiedBy
        ///   ,U.LastModifiedOn
        ///   ,R.Id RoleId
        ///   ,R.Name Name
        ///FROM [User] U WITH (NOLOCK)
        ///JOIN User_Role UR
        ///    ON U.Id = UR.UserId
        ///JOIN [Role] R
        ///    ON UR.RoleId = R.Id
        ///WHERE U.EmailActivationId = @EmailActivationId;.
        /// </summary>
        internal static string User_GetUserByEmailActivationId {
            get {
                return ResourceManager.GetString("User_GetUserByEmailActivationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    U.Id
        ///   ,U.FirstName
        ///   ,U.LastName
        ///   ,U.Email
        ///   ,U.Password
        ///   ,U.Status
        ///   ,U.EmailActivationId
        ///   ,U.ApiUrl
        ///   ,U.ApiGuid
        ///   ,U.TranscriptionEngineId
        ///   ,U.CreatedBy
        ///   ,U.CreatedOn
        ///   ,U.LastModifiedBy
        ///   ,U.LastModifiedOn
        ///   ,R.Id RoleId
        ///   ,R.Name
        ///FROM [User] U WITH (NOLOCK)
        ///JOIN User_Role UR
        ///    ON U.Id = UR.UserId
        ///JOIN [Role] R
        ///    ON UR.RoleId = R.Id
        ///WHERE U.Id = @UserId;.
        /// </summary>
        internal static string User_GetUserById {
            get {
                return ResourceManager.GetString("User_GetUserById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT TOP(1) [Id], [UserId], [LoginTime]
        ///FROM [UserLoginHistory] WITH (NOLOCK)
        ///WHERE [UserId] = @UserId
        ///ORDER BY [LoginTime] DESC.
        /// </summary>
        internal static string User_GetUserLoginHistoryByUserId {
            get {
                return ResourceManager.GetString("User_GetUserLoginHistoryByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [User]
        ///SET [TemporalPassword] = @TemporalPassword
        ///WHERE Id = @UserId.
        /// </summary>
        internal static string User_SetTemporalPassword {
            get {
                return ResourceManager.GetString("User_SetTemporalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [User]
        ///SET [Password] = @Password, [LastModifiedOn] = GETUTCDATE(), [LastModifiedBy] = @LastModifiedBy
        ///WHERE Id = @Id.
        /// </summary>
        internal static string User_UpdatePassword {
            get {
                return ResourceManager.GetString("User_UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [User]
        ///SET [Status] = @Status, [LastModifiedOn] = GETUTCDATE(), [LastModifiedBy] = @LastModifiedBy
        ///WHERE Id = @Id.
        /// </summary>
        internal static string User_UpdateStatus {
            get {
                return ResourceManager.GetString("User_UpdateStatus", resourceCulture);
            }
        }
    }
}
